// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/modern-apis-architecture/ledger/internal/adapter"
	"github.com/modern-apis-architecture/ledger/internal/domain/transaction/service"
	"github.com/modern-apis-architecture/ledger/internal/storage/mongo"
)

// Injectors from wire.go:

func buildAppContainer() (*adapter.LedgerServer, error) {
	collection, err := mongo.ProvideCollection()
	if err != nil {
		return nil, err
	}
	mongoTransactionRepository := mongo.NewMongoTransactionRepository(collection)
	transactionService := service.NewTransactionService(mongoTransactionRepository)
	ledgerServer := adapter.NewLedgerServer(transactionService)
	return ledgerServer, nil
}
